//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HorarioAtencion.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
private class HorarioAtencion {
    /** */
    private String dia;
    
    /** */
    private timestamp horainicio;
    
    /** */
    private timestamp horafin;
    
    /** */
    public void agregarTurno() {
    
    }
    
    /** */
    public void borrarTurno() {
    
    }
}
