//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotaConsulta.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class NotaConsulta {
    /** */
    private String síntomas;
    
    /** */
    private String diagnóstico;
    
    /** */
    private String indicaciones;
    
    /** */
    private String recetario;
    
    /** */
    private Float pesoactual;
    
    /** */
    private Float alturaactual;
    
    /** */
    private Integer edadactual;
    
    /** */
    private String unidadedad;
}
