//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reserva.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class Reserva {
    /** */
    private Date fecharealizacion;
    
    /** */
    private Date fechareservada;
    
    /** */
    private Boolean cancelado;
    
    /** */
    private String observcancelado;
    
    /** */
    public HorarioAtencion Unnamed1;
    
    /** */
    public Turno Unnamed4;
}
