//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Secretario.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class Secretario extends Usuario {
    /** */
    public void agregarReserva() {
    
    }
    
    /** */
    public void registrarPaciente() {
    
    }
    
    /** */
    public void cancelarReserva() {
    
    }
    
    /** */
    public void reprogramarReserva() {
    
    }
}
