//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TipoSangre.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class TipoSangre {
    /**
     * Nota para el DER: se podría implementar como una tabla ya predefinida de los tipos de sangre.
    **/
    private String tiposangre;
    
    /** */
    public Paciente Unnamed1;
}
