//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/**
 * Básicamente el sistema tiene usuarios, y estos pueden ser pacientes, doctores, administradores o asistentes. 
 * 
 * Es importante mencionar, que el rol paciente engloba a todos de nuevo ya que todos pueden ser pacientes del hospital.
 * 
 * Es decir, un doctor también puede enfermarse y tener un historial clínico en la clínica.
**/
public class Usuario {
    /** */
    private String userid;
    
    /** */
    private String password;
    
    /** */
    private Integer cedula;
    
    /** */
    private String nombre;
    
    /** */
    private String apellido;
    
    /** */
    private String género;
    
    /** */
    private String direccion;
    
    /** */
    private String telefono;
    
    /** */
    private String email;
    
    /** */
    private date Date;
    
    /**
     * Definición genérica de los Getters y Setters. En realidad debe haber uno por cada atributo de la clase
     *
     * @param    atributo
     * @param    valor
    **/
    public void getAttribute(String atributo, Object valor) {
    
    }
    
    /** */
    public void setAttribute(String atributo, Object valor) {
    
    }
}
