//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Administrador.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class Administrador extends Usuario {
    /** */
    public void crearUsuario(String nombre, String apellido, String cedula, String userid) {
    
    }
    
    /** */
    public void eliminarUsuario(String userid) {
    
    }
    
    /** */
    public void actualizarUsuario(String userid, String campo, String valor) {
    
    }
    
    /** */
    public void modificarHorariosDeAtencion() {
    
    }
}
