//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Consulta.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class Consulta {
    /** */
    private Date fecha;
    
    /** */
    private timestamp horainicio;
    
    /** */
    private timestamp horafin;
    
    /** */
    public Reserva Unnamed2;
    
    /** */
    public void agregarNota() {
    
    }
    
    /** */
    public void borrarNota() {
    
    }
}
