//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Doctor.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class Doctor extends Usuario {
    /** */
    public HorarioAtencion Unnamed1;
    
    /** */
    public Consulta Unnamed2;
    
    /** */
    public void atenderConsulta() {
    
    }
    
    /** */
    public void crearNotaDeConsulta() {
    
    }
    
    /** */
    public void consultarHistorialDePaciente() {
    
    }
    
    /** */
    public void cerrarConsulta() {
    
    }
    
    /** */
    public void verReservasPendientes() {
    
    }
}
