//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Especialidad.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class Especialidad {
    /** */
    private String descripcion;
    
    /** */
    private String nombre;
}
