//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Paciente.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class Paciente extends Usuario {
    /** */
    private Date fechaingreso;
    
    /** */
    public Reserva Unnamed1;
    
    /** */
    public Consulta Unnamed2;
    
    /** */
    public TipoSangre Unnamed3;
    
    /** */
    public void consultar() {
    
    }
    
    /** */
    public void revisarHistorial() {
    
    }
    
    /** */
    public void exportarHistorial() {
    
    }
    
    /** */
    public void imprimirHistorial() {
    
    }
    
    /** */
    public void revisarNotaConsulta() {
    
    }
    
    /** */
    public void agregarReserva() {
    
    }
    
    /** */
    public void cancelarReserva() {
    
    }
    
    /** */
    public void reprogramarReserva() {
    
    }
}
