//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Turno.java
//  @ Date : 08/10/2007
//  @ Author : 
//
//




/** */
public class Turno {
    /** */
    private timestamp hora;
}
